### ISSUE TITLE
Compatibility with Astroconda

### ISSUE THREAD

**Issue by genghisken** [svalenti/pessto#45]
I've just attempted to install the pipeline using astroconda / iraf27 (currently using El Capitan)

The code installs OK, but when I run PESSTOFASTSPEC to test the pipeline, I get the following message (presumably a problem with usage of PyFITS)

```
PESSTOFASTSPEC -i -C EFOSC.2017-04-30T05:37:38.416.fits

####  image name = EFOSC.2017-04-30T05:37:38.416.fits

EFOSC.2017-04-30T05:37:38.416.fits -> tAT2017dju_20170429_Gr13_Free_slit1.0_1.fits

### cosmic rays rejections ........ done 
cp: ./arc_20120825_Gr13_Free_slit1.0_56442_1.fits and arc_20120825_Gr13_Free_slit1.0_56442_1.fits are identical (not copied).
Traceback (most recent call last):
  File "/Users/kws/nttpipeline2215_conda/bin/PESSTOFASTSPEC", line 4, in <module>
    __import__('pkg_resources').run_script('ntt==2.2.14', 'PESSTOFASTSPEC')
  File "/Users/kws/anaconda/envs/iraf27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
    
  File "/Users/kws/anaconda/envs/iraf27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
    
  File "/Users/kws/nttpipeline2215_conda/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/EGG-INFO/scripts/PESSTOFASTSPEC", line 45, in <module>
    _interactive)
  File "/Users/kws/nttpipeline2215_conda/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/ntt/efoscfastspecdef.py", line 146, in efoscfastredu
    shift = ntt.efoscspec2Ddef.skyfrom2d(img, _skyfile)
  File "/Users/kws/nttpipeline2215_conda/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/ntt/efoscspec2Ddef.py", line 108, in skyfrom2d
    hdulist[0].header.update('CRVAL1', crval2)
  File "/Users/kws/anaconda/envs/iraf27/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1116, in update
    'a keyword, value, and comment string.'.format(idx))
ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.
```

**Comment by svalenti** [comment]
which version of the pipeline did you install?
I made some changes that that I'm not sure are propagated in the last tar file

**Comment by svalenti** [comment]
I installed miniconda and astroconda and made the change that was giving the error
please test

**Comment by svalenti** [comment]
I think the pipeline is now Astro Conda compatible (tested on few data), but it would be good if someone can do more tests

**Comment by genghisken** [comment]
OK.  This seems to work OK, though I've only tested PESSTOEFOSCPHOT so far.  I'll get Erkki to test the SOFI components.  Note that we should package up the latest release as a downloadable release, including updating the release number file.

**Comment by ekankare** [comment]
Still running El Capitan and Ureka. I tested PESSTOSOFIPHOT from the master branch. SOFI image reduction does not seem to work. It is still an issue with calling 2MASS. Though now it might be related to the data format rather than the path? 


vizquery -mime=tsv  -site=vizier.u-strasbg.fr -source=II/246/out -c.ra=41.31684 -c.dec=-55.72422 -c.eq=J2000 -c.rm=10 -c.geom=b -oc.form=h -sort=_RA*-c.eq -out.add=_RAJ2000,_DEJ2000 -out.max=10000 -out=2MASS -out=Jmag
#...ASU parameters being sent to vizier
Traceback (most recent call last):
  File "/Users/eskank/tools/Ureka/variants/common/bin/PESSTOSOFIPHOT", line 5, in <module>
    pkg_resources.run_script('ntt==2.2.14', 'PESSTOSOFIPHOT')
  File "/Users/eskank/tools/Ureka/python/lib/python2.7/site-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/eskank/tools/Ureka/python/lib/python2.7/site-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Users/eskank/tools/Ureka/variants/common/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/EGG-INFO/scripts/PESSTOSOFIPHOT", line 98, in <module>
    _interactive, _regi, _verbose, method)
  File "/Users/eskank/tools/Ureka/variants/common/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/ntt/sofiphotredudef.py", line 1213, in sofireduction
    nameobjnew, '2mass', method, False, False)
  File "/Users/eskank/tools/Ureka/variants/common/lib/python2.7/site-packages/ntt-2.2.14-py2.7.egg/ntt/efoscastrodef.py", line 438, in zeropoint
    stdcoo[ww] = stdcoo[colasci[ww]]
KeyError: 'mag2'

**Comment by svalenti** [comment]
Please give the set of images you are trying to process

**Comment by svalenti** [comment]
I was switching to use always the function vizq2, instead of using sometimes vizq and other time vizq2. I introduced a bug that now I have fixed in the last commit.
more test are needed to be sure that astrometry and zeropoint work for efosc images
