### ISSUE TITLE
PermissionError: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by pjpessi** [svalenti/pessto#60]
After extracting the spectrum I get the permission error I pasted below. Last time I installed the pipeline I got the same error and I changed some permissions and it was fixed. Thing is, I forgot which permissions I changed.
Could you help me out here? :)

````
Fit spectrum for aperture 1 for flat_2020.fits interactively? ('yes'): 
### replace pixel 1:200 with 1 (y axes)
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
### EFOSC.2020.fits  ->  L745a_2020.fits 

[ ]

[ ]
Traceback (most recent call last):
  File "/home/anaconda3/envs/python3/bin/PESSTOEFOSC2dSPEC", line 4, in <module>
    __import__('pkg_resources').run_script('ntt==3.0.1', 'PESSTOEFOSC2dSPEC')
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/ntt-3.0.1-py3.7.egg/EGG-INFO/scripts/PESSTOEFOSC2dSPEC", line 112, in <module>
    listbias, listarc, _cosmic, _verbose)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/ntt-3.0.1-py3.7.egg/ntt/efoscspec2Ddef.py", line 766, in efoscspecreduction
    sigfrac=0.5, objlim=1, verbose=True, interactive=False)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/ntt-3.0.1-py3.7.egg/ntt/cosmics.py", line 151, in lacos
    '**2)/' + str(gain), a=med5, output=noise, verbose='no')
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pyraf/iraftask.py", line 834, in __call__
    return self.run(*args, **kw)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pyraf/iraftask.py", line 374, in run
    self._updateParList(save)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pyraf/iraftask.py", line 918, in _updateParList
    rv = self.saveParList()
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pyraf/iraftask.py", line 762, in saveParList
    rv = self._currentParList.saveParList(filename, comment)
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/pyraf/irafpar.py", line 1112, in saveParList
```
    os.makedirs(absDir)
  File "/home/anaconda3/envs/python3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/anaconda3/envs/python3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/anaconda3/envs/python3/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/home/anaconda3/envs/python3/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch'`

**Comment by temuller** [comment]
This issue does not seem to come from the pipeline itself, but from your user permission.  Not sure what might have caused this (maybe it has to do with your MacOS?). Maybe at some point along the many installation steps you used ``sudo`` when it was not necessary and is causing now the problem. You can try running the pipeline as a super user or try reinstalling it (I know this is a pain) to see if that solves it.  I'll see if I can find more information on this.

**Comment by temuller** [comment]
Maybe it is related to [creating a directory inside the root directory](https://stackoverflow.com/questions/32329976/makedirs-gives-oserror-errno-13-permission-denied-pdf-files), but I don't know how that could happen in your case.

**Comment by pjpessi** [comment]
Hi Tomas, I don't have MacOS. I have linux (Debian). I installed the pipeline following the steps in the README.md. I think it's the pipeline trying to create a file, but I am not sure where. I will install everything again from scratch (I've already deleted the pessto folder and installed it again), maybe it's something with iraf.

**Comment by pjpessi** [comment]
Ok, sigh... I solved it, it was my own silliness and not the pipeline. Sorry Tomas for wasting your time.

For own future reference I describe all the details here (it was a very silly issue, sigh again). 
After installing I run the test (PESSTOFASTSPEC -i EFOSC.2012-04-12T00\:21\:13.429.fits) and I get:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/matplotlib/_pylab_helpers.py", line 90, in destroy_all
    manager.destroy()
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 513, in destroy
    delayed_destroy()
  File "/home/anaconda3/envs/python3/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 503, in delayed_destroy
    self.window.destroy()
  File "/home/anaconda3/envs/python3/lib/python3.7/tkinter/__init__.py", line 2062, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
```
I downgrade matplotlib version to 3.5.1 and I get

```
    while executing
"140465201522480after"
    ("after" script)
```

Which I guess is correct.
I then go try a science spectrum and I get the original error. The permission error is of pyraf, it also occurs when performing other tasks (such as splot), this is because I had an old login.cl, to solve it run `mkiraf` to get a new login.cl

**Comment by temuller** [comment]
good to see you solved this problem :+1: also thanks for posting the solution. Closing the issue now.
